version: '3.8'

services:
  web:
    image: ghcr.io/YOUR_GITHUB_USERNAME/next-tracker:latest
    container_name: next-tracker
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/prisma

volumes:
  sqlite_data:
